# Generated by Django 4.2.16 on 2024-10-04 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user_departments.userdepartment')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user_roles.userrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['id'],
            },
        ),
    ]
