# Generated by Django 4.2.16 on 2024-10-06 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartFocus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.TextField(max_length=256, verbose_name='text')),
            ],
            options={
                'db_table': 'chart_focus',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChartInterviewed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.CharField(max_length=256, verbose_name='text')),
            ],
            options={
                'db_table': 'chart_interviewed',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChartRequirement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.CharField(max_length=256, verbose_name='text')),
            ],
            options={
                'db_table': 'chart_requirement',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.CharField(max_length=256, verbose_name='text')),
            ],
            options={
                'db_table': 'chart_types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('code', models.CharField(max_length=256, verbose_name='code')),
                ('justification', models.TextField(max_length=256, null=True, verbose_name='justification')),
                ('women', models.BooleanField(default=True, verbose_name='women')),
                ('sustainable', models.BooleanField(default=True, verbose_name='sustainable')),
                ('url', models.CharField(blank=True, max_length=256, verbose_name='url')),
                ('success', models.BooleanField(default=False, verbose_name='success')),
                ('success_date', models.DateField(null=True, verbose_name='success date')),
                ('description', models.TextField(blank=True, max_length=256, verbose_name='description')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.CharField(max_length=256, verbose_name='text')),
            ],
            options={
                'db_table': 'project_fail',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
            ],
            options={
                'db_table': 'user_department',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
            ],
            options={
                'db_table': 'user_role',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SensorChart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('executive', models.BooleanField(default=True, verbose_name='executive')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('sensor_chart_date', models.DateField(verbose_name='sensor chart date')),
                ('first_evidence', models.TextField(max_length=256, verbose_name='first evidence')),
                ('second_evidence', models.TextField(max_length=256, verbose_name='second evidence')),
                ('third_evidence', models.TextField(max_length=256, verbose_name='third evidence')),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='comment')),
                ('focus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.chartfocus')),
                ('interviewed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.chartinterviewed')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.project')),
                ('requirement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.chartrequirement')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.charttype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.employee')),
            ],
            options={
                'db_table': 'sensor_chart',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='fail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.projectfail'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='innovasensorapp.userdepartment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='innovasensorapp.userrole'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
