# Generated by Django 4.2.16 on 2024-10-06 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovasensorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fail_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.projectfail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
