# Generated by Django 4.2.16 on 2024-10-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovasensorapp', '0002_alter_project_fail_id_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='justification',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='justification'),
        ),
        migrations.AlterField(
            model_name='project',
            name='success',
            field=models.BooleanField(blank=True, null=True, verbose_name='success'),
        ),
        migrations.AlterField(
            model_name='project',
            name='success_date',
            field=models.DateField(blank=True, null=True, verbose_name='success date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sustainable',
            field=models.BooleanField(blank=True, null=True, verbose_name='sustainable'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='project',
            name='women',
            field=models.BooleanField(blank=True, null=True, verbose_name='women'),
        ),
    ]
