# Generated by Django 4.2.16 on 2024-10-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovasensorapp', '0004_alter_chartfocus_id_alter_chartinterviewed_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorchart',
            name='focus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.chartfocus'),
        ),
        migrations.AlterField(
            model_name='sensorchart',
            name='interviewed_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.chartinterviewed'),
        ),
        migrations.AlterField(
            model_name='sensorchart',
            name='requirement_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.chartrequirement'),
        ),
        migrations.AlterField(
            model_name='sensorchart',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.charttype'),
        ),
    ]
