# Generated by Django 4.2.16 on 2024-10-06 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovasensorapp', '0005_alter_sensorchart_focus_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorchart',
            old_name='user_id',
            new_name='employee_id',
        ),
    ]
