# Generated by Django 4.2.16 on 2024-10-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovasensorapp', '0006_rename_user_id_sensorchart_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorchart',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
