# Generated by Django 4.2.16 on 2024-10-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovasensorapp', '0007_alter_sensorchart_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorchart',
            old_name='type_id',
            new_name='chart_type',
        ),
        migrations.RenameField(
            model_name='sensorchart',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='sensorchart',
            old_name='focus_id',
            new_name='focus',
        ),
        migrations.RenameField(
            model_name='sensorchart',
            old_name='interviewed_id',
            new_name='interviewed',
        ),
        migrations.RenameField(
            model_name='sensorchart',
            old_name='project_id',
            new_name='project',
        ),
    ]
