# Generated by Django 4.2.16 on 2024-10-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovasensorapp', '0008_rename_type_id_sensorchart_chart_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorchart',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
