# Generated by Django 4.2.16 on 2024-10-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovasensorapp', '0009_rename_employee_sensorchart_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorchart',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
