# Generated by Django 4.2.16 on 2024-10-06 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovasensorapp', '0011_rename_department_id_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorchart',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.employee'),
        ),
    ]
