# Generated by Django 4.2.16 on 2024-10-06 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovasensorapp', '0013_alter_sensorchart_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorchart',
            name='employee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorchart',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innovasensorapp.project'),
        ),
    ]
