# Generated by Django 4.2.16 on 2024-10-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
            ],
            options={
                'db_table': 'user_department',
                'ordering': ['id'],
            },
        ),
    ]
